### ISSUE TITLE
Help: making

### ISSUE THREAD

**Issue by strikersix23** [FWGS/xash-extras#12]
Is there a tutorial on how to build, I am an absolute noob so any guidance would be nice

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/master/README.md

**Comment by strikersix23** [comment]
I ment the extras.pak

**Comment by nekonomicon** [comment]
You can use [our script](https://github.com/FWGS/xash3d-fwgs/blob/master/scripts/makepak.py), [GCFScape](https://nemstools.github.io/pages/GCFScape.html) or [nwreckdum](https://github.com/danfe/nwreckdum).
