### ISSUE TITLE
Лишние файлы.

### ISSUE THREAD

**Issue by nekonomicon** [FWGS/xash-extras#6]
В steam HL до сих пор присутствуют файлы из списка ниже:
```
credits.txt
gfx/shell/kb_act.lst
gfx/shell/kb_def.lst
gfx/shell/kb_keys.lst
```
При этом содержимое ничем не отличается.
Думаю, мы ничего не потеряем если просто удалим их.

Еще вопрос в целесообразности распространения `colors.lst`.
Возможно, будет лучше эти числа захардкодить, а при наличии в моде такого файла, читать значения из файла.

**Comment by lewa-j** [comment]
Содержимое kb_act.lst отлитчается. В стиме там строки вроде "#Valve_Movement_Title", а тут обычный текст. У ДМ эти файлы были из-за отсутствия системы локализации, нам они уже не нужны.

**Comment by nekonomicon** [comment]
Не актуально с последними изменениями.
